name: tdd_clean_app
description: Flutter com TDD e clean.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.22.0
  mockito: ^5.4.0
  faker: ^2.1.0

flutter:

  uses-material-design: true
